# Generated by Django 4.1.5 on 2023-02-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockaccount',
            name='account_id',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, unique=True),
        ),
    ]
