# Generated by Django 4.1.5 on 2023-02-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockaccount',
            name='user',
        ),
    ]
