# Generated by Django 4.1.5 on 2023-03-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='security_id',
            field=models.CharField(max_length=100),
        ),
    ]
