# Generated by Django 4.1.5 on 2023-02-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockaccount_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('lon', models.FloatField(blank=True, default=None, null=True)),
                ('store_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('iso_currency_code', models.CharField(max_length=30, null=True)),
                ('unofficial_currency_code', models.CharField(max_length=100, null=True)),
                ('category', models.JSONField()),
                ('category_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('authorized_datetime', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('merchant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_channel', models.CharField(choices=[('online', 'Online'), ('in store', 'In Store'), ('other', 'Other')], max_length=20)),
                ('pending', models.BooleanField()),
                ('pending_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_code', models.CharField(blank=True, choices=[('adjustment', 'Adjustment'), ('atm', 'ATM'), ('bank charge', 'Bank charge'), ('bill payment', 'Bill payment'), ('cash', 'Cash'), ('cashback', 'Cashback'), ('cheque', 'Cheque'), ('direct debit', 'Direct debit'), ('interest', 'Interest'), ('purchase', 'Purchase'), ('standing order', 'Standing order'), ('transfer', 'Transfer')], max_length=30, null=True)),
                ('transaction_type', models.CharField(choices=[('digital', 'Digital'), ('place', 'Special'), ('special', 'Special'), ('unresolved', 'Unresolved')], max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.location')),
            ],
        ),
    ]
