# Generated by Django 4.1.5 on 2023-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_location_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=models.JSONField(),
        ),
    ]
