# Generated by Django 4.1.5 on 2023-03-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_transaction_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='stocks.stockaccount'),
        ),
    ]
