# Generated by Django 4.1.5 on 2023-03-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_transaction_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
    ]
