# Generated by Django 4.1.5 on 2023-02-24 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='free',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='token',
            name='locked',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
