# Generated by Django 4.1.5 on 2023-02-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binanceaccount',
            name='access_token',
        ),
        migrations.AddField(
            model_name='binanceaccount',
            name='api_key',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binanceaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binanceaccount',
            name='secret_key',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
