# Generated by Django 4.1.5 on 2023-03-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0002_alter_token_free_alter_token_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='crypto_exchange',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto_exchanges.cryptoexchangeaccount'),
            preserve_default=False,
        ),
    ]
