# Generated by Django 4.1.5 on 2023-03-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0003_token_crypto_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptoexchangeaccount',
            old_name='crypto_exchange',
            new_name='crypto_exchange_name',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='crypto_exchange',
            new_name='crypto_exchange_object',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='free',
            new_name='free_amount',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='locked',
            new_name='locked_amount',
        ),
    ]
