# Generated by Django 4.1.5 on 2023-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0004_rename_crypto_exchange_cryptoexchangeaccount_crypto_exchange_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='asset',
            field=models.CharField(max_length=5),
        ),
    ]
