# Generated by Django 4.1.5 on 2023-02-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0005_remove_token_account_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='asset',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
