# Generated by Django 4.1.5 on 2023-02-23 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_exchanges', '0008_gateioaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_exchange', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coinlistaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gateioaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='huobiaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='token',
            name='asset',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.DeleteModel(
            name='BinanceAccount',
        ),
        migrations.DeleteModel(
            name='CoinListAccount',
        ),
        migrations.DeleteModel(
            name='GateioAccount',
        ),
        migrations.DeleteModel(
            name='HuobiAccount',
        ),
    ]
