# Generated by Django 4.1.5 on 2023-02-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_exchanges', '0009_cryptoexchangeaccount_remove_coinlistaccount_user_and_more'),
        ('crypto_exchanges', '0010_alter_token_free_alter_token_locked_coinbaseaccount'),
    ]

    operations = [
    ]
