# Generated by Django 4.1.5 on 2023-02-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('refresh_token', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token_expiration', models.DateTimeField()),
                ('access_token_expiration', models.DateTimeField()),
            ],
        ),
    ]
