# Generated by Django 4.1.5 on 2023-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
