# Generated by Django 4.1.5 on 2023-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_account_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
    ]
