# Generated by Django 4.1.5 on 2023-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='iban',
            field=models.CharField(default='1', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='institution_id',
            field=models.CharField(default='1', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='institution_logo',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='institution_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
